# Generated by Django 6.0 on 2025-12-19 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('SUCCEEDED', 'Succeeded'), ('REFUNDED', 'Refunded'), ('FAILED', 'Failed')], default='CREATED', max_length=20),
        ),
    ]
