# Generated by Django 6.0 on 2026-02-03 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='desktop_image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/desktop/'),
        ),
        migrations.AddField(
            model_name='category',
            name='mobile_image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/mobile/'),
        ),
        migrations.AddField(
            model_name='category',
            name='mobile_secondary_image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/mobile_secondary/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/common/'),
        ),
    ]
