# Generated by Django 6.0 on 2026-02-07 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_desktop_image_category_mobile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='desktop_secondary_image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/desktop_secondary'),
        ),
    ]
